# Generated by Django 3.2 on 2021-05-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='add_datetime',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='quantity',
        ),
    ]
